### ISSUE TITLE
container-usage has missing link to cont-lib directory hierarchy

### ISSUE THREAD

**Issue by pbabinca** [fedora-cloud/Fedora-Dockerfiles#120]
Command:
 `# docker run username/postgresql container-usage`
has reference to `[2]` but actual target for this reference is missing.

**Comment by praiskup** [comment]
Thanks for the report, fedora-cloud/Fedora-Dockerfiles/pull/125 should fix this.

**Comment by praiskup** [comment]
I do not have permissions to close this -- but fixed as #125, #126 and #127
