### ISSUE TITLE
/bin/sh: find: command not found

### ISSUE THREAD

**Issue by zeitos** [fedora-cloud/Fedora-Dockerfiles#152]
Does anyone know how to add find command to fedora images?

```
FROM fedora
MAINTAINER ZeoS

RUN yum -y update && yum clean all
RUN find .
CMD ["bash"]
```

results in 

```
/bin/sh: find: command not found
```

**Comment by praveenkumar** [comment]
```
FROM fedora:latest
MAINTAINER <Name/mail-id>

RUN dnf -y update && \
        dnf install findutils && \
        dnf clean all
RUN find .
CMD ["bash"]
```
**findutils** is provide find binary and if you are using fedora latest image then I would suggest you to use **dnf** instead of **yum**

**Comment by scollier** [comment]
@zeitos this all good now?  We have switched all the Dockerfiles in master to use dnf as @praveenkumar  stated.

**Comment by zeitos** [comment]
all good, thanks
