### ISSUE TITLE
How to change the password?

### ISSUE THREAD

**Issue by Aarushi-Ign** [fedora-cloud/Fedora-Dockerfiles#167]
The password mentioned in DockerFile is 123456. I need to change this password and rebuild. Where is it listed?

**Comment by adelton** [comment]
I assume this is about `firefox/Dockerfile`. You should be able to just run the container with `docker run -v /your/file/with/password:/root/.vnc/passwd:ro` to override the default.

**Comment by Aarushi-Ign** [comment]
thanks
