### ISSUE TITLE
Firefox container doesn't seem to work as detailed in README.md

### ISSUE THREAD

**Issue by kfiresmith** [fedora-cloud/Fedora-Dockerfiles#60]
[me@mybox firefox]$ docker logs pensive_goodall

You will require a password to access your desktops.

getpassword error: Inappropriate ioctl for device

[me@mybox firefox]$ vncviewer localhost:1

TigerVNC Viewer 64-bit v1.3.0 (20140319)
Built on Mar 19 2014 at 17:09:18
Copyright (C) 1999-2011 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Thu Dec  4 20:38:53 2014
 CConn:       unable connect to socket: Connection refused (111)

Tested on up-to-date Fedora 20 workstation.

**Comment by mikedep333** [comment]
I just reproduced this on Fedora 21.
