### ISSUE TITLE
Docker base image for Cloud spins

### ISSUE THREAD

**Issue by stereoit** [fedora-cloud/Fedora-Dockerfiles#64]
Hello,
is it possible to create dockerfile using the Fedora 21 Cloud images? https://getfedora.org/en/cloud/download/ lists image for general purpose and one for containers, I would like to base my work on those.

So what repo/image shall I use in FROM statement?

**Comment by scollier** [comment]
Hi @stereoit , if you want to use a Fedora 21 image, please just include a:

FROM fedora:21 

At the beginning of your Dockerfile.

The Fedora Docker base images are different than the cloud images.  More information here:

https://registry.hub.docker.com/_/fedora/
