### ISSUE TITLE
"passwd: command not found" when building the image

### ISSUE THREAD

**Issue by arun-gupta** [fedora-cloud/Fedora-Dockerfiles#65]
Building the image gives the following error:

Step 8 : RUN ./start.sh
 ---> Running in b2614be2ddbe
./start.sh: line 7: passwd: command not found
ssh user password: newpass
 ---> 54112ab06e1c

Complete log:
docker build --rm=true -t arungupta/ssh .
Sending build context to Docker daemon 2.512 MB
Sending build context to Docker daemon 
Step 0 : FROM fedora
Pulling repository fedora
834629358fe2: Download complete 
511136ea3c5a: Download complete 
00a0c78eeb6d: Download complete 
Status: Downloaded newer image for fedora:latest
 ---> 834629358fe2
Step 1 : MAINTAINER scollier <scollier@redhat.com>
 ---> Running in 62bc6df8c503
 ---> ae8fcaf981a3
Removing intermediate container 62bc6df8c503
Step 2 : RUN yum -y update && yum clean all
 ---> Running in abf6034f4b03
Resolving Dependencies
--> Running transaction check
---> Package cpio.x86_64 0:2.11-30.fc21 will be updated
---> Package cpio.x86_64 0:2.11-33.fc21 will be an update
---> Package curl.x86_64 0:7.37.0-9.fc21 will be updated
---> Package curl.x86_64 0:7.37.0-11.fc21 will be an update
---> Package dbus.x86_64 1:1.8.6-3.fc21 will be updated
---> Package dbus.x86_64 1:1.8.12-3.fc21 will be an update
---> Package dbus-libs.x86_64 1:1.8.6-3.fc21 will be updated
---> Package dbus-libs.x86_64 1:1.8.12-3.fc21 will be an update
---> Package dracut.x86_64 0:038-30.git20140903.fc21 will be updated
---> Package dracut.x86_64 0:038-32.git20141216.fc21 will be an update
---> Package filesystem.x86_64 0:3.2-27.fc21 will be updated
---> Package filesystem.x86_64 0:3.2-28.fc21 will be an update
---> Package firewalld.noarch 0:0.3.12-1.fc21 will be updated
---> Package firewalld.noarch 0:0.3.13-1.fc21 will be an update
--> Processing Dependency: firewalld-filesystem = 0.3.13-1.fc21 for package: firewalld-0.3.13-1.fc21.noarch
---> Package firewalld-config-standard.noarch 0:0.3.12-1.fc21 will be updated
---> Package firewalld-config-standard.noarch 0:0.3.13-1.fc21 will be an update
---> Package freetype.x86_64 0:2.5.3-11.fc21 will be updated
---> Package freetype.x86_64 0:2.5.3-13.fc21 will be an update
---> Package gettext.x86_64 0:0.19.2-6.fc21 will be updated
---> Package gettext.x86_64 0:0.19.4-2.fc21 will be an update
---> Package gettext-libs.x86_64 0:0.19.2-6.fc21 will be updated
---> Package gettext-libs.x86_64 0:0.19.4-2.fc21 will be an update
---> Package gpgme.x86_64 0:1.4.3-4.fc21 will be updated
---> Package gpgme.x86_64 0:1.4.3-5.fc21 will be an update
---> Package grep.x86_64 0:2.20-6.fc21 will be updated
---> Package grep.x86_64 0:2.21-1.fc21 will be an update
---> Package grub2.x86_64 1:2.02-0.11.fc21 will be updated
---> Package grub2.x86_64 1:2.02-0.13.fc21 will be an update
---> Package grub2-tools.x86_64 1:2.02-0.11.fc21 will be updated
---> Package grub2-tools.x86_64 1:2.02-0.13.fc21 will be an update
---> Package kmod.x86_64 0:18-4.fc21 will be updated
---> Package kmod.x86_64 0:19-1.fc21 will be an update
---> Package kmod-libs.x86_64 0:18-4.fc21 will be updated
---> Package kmod-libs.x86_64 0:19-1.fc21 will be an update
---> Package libblkid.x86_64 0:2.25.2-1.fc21 will be updated
---> Package libblkid.x86_64 0:2.25.2-2.fc21 will be an update
---> Package libcurl.x86_64 0:7.37.0-9.fc21 will be updated
---> Package libcurl.x86_64 0:7.37.0-11.fc21 will be an update
---> Package libmount.x86_64 0:2.25.2-1.fc21 will be updated
---> Package libmount.x86_64 0:2.25.2-2.fc21 will be an update
---> Package libsmartcols.x86_64 0:2.25.2-1.fc21 will be updated
---> Package libsmartcols.x86_64 0:2.25.2-2.fc21 will be an update
---> Package libuuid.x86_64 0:2.25.2-1.fc21 will be updated
---> Package libuuid.x86_64 0:2.25.2-2.fc21 will be an update
---> Package nss.x86_64 0:3.17.2-1.fc21 will be updated
---> Package nss.x86_64 0:3.17.3-2.fc21 will be an update
---> Package nss-softokn.x86_64 0:3.17.2-1.fc21 will be updated
---> Package nss-softokn.x86_64 0:3.17.3-1.fc21 will be an update
---> Package nss-softokn-freebl.x86_64 0:3.17.2-1.fc21 will be updated
---> Package nss-softokn-freebl.x86_64 0:3.17.3-1.fc21 will be an update
---> Package nss-sysinit.x86_64 0:3.17.2-1.fc21 will be updated
---> Package nss-sysinit.x86_64 0:3.17.3-2.fc21 will be an update
---> Package nss-tools.x86_64 0:3.17.2-1.fc21 will be updated
---> Package nss-tools.x86_64 0:3.17.3-2.fc21 will be an update
---> Package nss-util.x86_64 0:3.17.2-1.fc21 will be updated
---> Package nss-util.x86_64 0:3.17.3-1.fc21 will be an update
---> Package os-prober.x86_64 0:1.58-11.fc21 will be updated
---> Package os-prober.x86_64 0:1.65-2.fc21 will be an update
---> Package pcre.x86_64 0:8.35-7.fc21 will be updated
---> Package pcre.x86_64 0:8.35-8.fc21 will be an update
---> Package procps-ng.x86_64 0:3.3.10-4.fc21 will be updated
---> Package procps-ng.x86_64 0:3.3.10-5.fc21 will be an update
---> Package rpm.x86_64 0:4.12.0.1-3.fc21 will be updated
---> Package rpm.x86_64 0:4.12.0.1-4.fc21 will be an update
---> Package rpm-build-libs.x86_64 0:4.12.0.1-3.fc21 will be updated
---> Package rpm-build-libs.x86_64 0:4.12.0.1-4.fc21 will be an update
---> Package rpm-libs.x86_64 0:4.12.0.1-3.fc21 will be updated
---> Package rpm-libs.x86_64 0:4.12.0.1-4.fc21 will be an update
---> Package rpm-plugin-selinux.x86_64 0:4.12.0.1-3.fc21 will be updated
---> Package rpm-plugin-selinux.x86_64 0:4.12.0.1-4.fc21 will be an update
---> Package rpm-python.x86_64 0:4.12.0.1-3.fc21 will be updated
---> Package rpm-python.x86_64 0:4.12.0.1-4.fc21 will be an update
---> Package sqlite.x86_64 0:3.8.7-1.fc21 will be updated
---> Package sqlite.x86_64 0:3.8.7.4-1.fc21 will be an update
---> Package systemd.x86_64 0:216-12.fc21 will be updated
---> Package systemd.x86_64 0:216-13.fc21 will be an update
---> Package systemd-libs.x86_64 0:216-12.fc21 will be updated
---> Package systemd-libs.x86_64 0:216-13.fc21 will be an update
---> Package tzdata.noarch 0:2014i-1.fc21 will be updated
---> Package tzdata.noarch 0:2014j-1.fc21 will be an update
---> Package util-linux.x86_64 0:2.25.2-1.fc21 will be updated
---> Package util-linux.x86_64 0:2.25.2-2.fc21 will be an update
--> Running transaction check
---> Package firewalld-filesystem.noarch 0:0.3.13-1.fc21 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                     Arch     Version                   Repository
                                                                           Size
================================================================================
Updating:
 cpio                        x86_64   2.11-33.fc21              updates   216 k
 curl                        x86_64   7.37.0-11.fc21            updates   270 k
 dbus                        x86_64   1:1.8.12-3.fc21           updates   351 k
 dbus-libs                   x86_64   1:1.8.12-3.fc21           updates   167 k
 dracut                      x86_64   038-32.git20141216.fc21   updates   316 k
 filesystem                  x86_64   3.2-28.fc21               updates   1.1 M
 firewalld                   noarch   0.3.13-1.fc21             updates   497 k
 firewalld-config-standard   noarch   0.3.13-1.fc21             updates    45 k
 freetype                    x86_64   2.5.3-13.fc21             updates   407 k
 gettext                     x86_64   0.19.4-2.fc21             updates   1.0 M
 gettext-libs                x86_64   0.19.4-2.fc21             updates   272 k
 gpgme                       x86_64   1.4.3-5.fc21              updates   157 k
 grep                        x86_64   2.21-1.fc21               updates   363 k
 grub2                       x86_64   1:2.02-0.13.fc21          updates   3.8 M
 grub2-tools                 x86_64   1:2.02-0.13.fc21          updates   7.3 M
 kmod                        x86_64   19-1.fc21                 updates   108 k
 kmod-libs                   x86_64   19-1.fc21                 updates    60 k
 libblkid                    x86_64   2.25.2-2.fc21             updates   175 k
 libcurl                     x86_64   7.37.0-11.fc21            updates   241 k
 libmount                    x86_64   2.25.2-2.fc21             updates   190 k
 libsmartcols                x86_64   2.25.2-2.fc21             updates   134 k
 libuuid                     x86_64   2.25.2-2.fc21             updates    77 k
 nss                         x86_64   3.17.3-2.fc21             updates   846 k
 nss-softokn                 x86_64   3.17.3-1.fc21             updates   308 k
 nss-softokn-freebl          x86_64   3.17.3-1.fc21             updates   207 k
 nss-sysinit                 x86_64   3.17.3-2.fc21             updates    53 k
 nss-tools                   x86_64   3.17.3-2.fc21             updates   481 k
 nss-util                    x86_64   3.17.3-1.fc21             updates    80 k
 os-prober                   x86_64   1.65-2.fc21               updates    46 k
 pcre                        x86_64   8.35-8.fc21               updates   477 k
 procps-ng                   x86_64   3.3.10-5.fc21             updates   381 k
 rpm                         x86_64   4.12.0.1-4.fc21           updates   500 k
 rpm-build-libs              x86_64   4.12.0.1-4.fc21           updates   110 k
 rpm-libs                    x86_64   4.12.0.1-4.fc21           updates   275 k
 rpm-plugin-selinux          x86_64   4.12.0.1-4.fc21           updates    48 k
 rpm-python                  x86_64   4.12.0.1-4.fc21           updates    90 k
 sqlite                      x86_64   3.8.7.4-1.fc21            updates   449 k
 systemd                     x86_64   216-13.fc21               updates   5.1 M
 systemd-libs                x86_64   216-13.fc21               updates   318 k
 tzdata                      noarch   2014j-1.fc21              updates   419 k
 util-linux                  x86_64   2.25.2-2.fc21             updates   2.0 M
Installing for dependencies:
 firewalld-filesystem        noarch   0.3.13-1.fc21             updates    44 k

Transaction Summary
================================================================================
Install              ( 1 Dependent package)
Upgrade  41 Packages

Total download size: 29 M
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
--------------------------------------------------------------------------------
Total                                              2.6 MB/s |  29 MB  00:11     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : nss-util-3.17.3-1.fc21.x86_64                               1/83 
  Updating   : systemd-libs-216-13.fc21.x86_64                             2/83 
  Updating   : libuuid-2.25.2-2.fc21.x86_64                                3/83 
  Updating   : libblkid-2.25.2-2.fc21.x86_64                               4/83 
  Updating   : nss-softokn-freebl-3.17.3-1.fc21.x86_64                     5/83 
  Updating   : kmod-libs-19-1.fc21.x86_64                                  6/83 
  Updating   : kmod-19-1.fc21.x86_64                                       7/83 
  Updating   : libmount-2.25.2-2.fc21.x86_64                               8/83 
  Updating   : procps-ng-3.3.10-5.fc21.x86_64                              9/83 
  Updating   : cpio-2.11-33.fc21.x86_64                                   10/83 
  Installing : firewalld-filesystem-0.3.13-1.fc21.noarch                  11/83 
  Updating   : filesystem-3.2-28.fc21.x86_64                              12/83 
  Updating   : libsmartcols-2.25.2-2.fc21.x86_64                          13/83 
  Updating   : util-linux-2.25.2-2.fc21.x86_64                            14/83 
  Updating   : freetype-2.5.3-13.fc21.x86_64                              15/83 
  Updating   : pcre-8.35-8.fc21.x86_64                                    16/83 
  Updating   : grep-2.21-1.fc21.x86_64                                    17/83 
install-info: No such file or directory for /usr/share/info/grep.info.gz
  Updating   : sqlite-3.8.7.4-1.fc21.x86_64                               18/83 
  Updating   : nss-softokn-3.17.3-1.fc21.x86_64                           19/83 
  Updating   : nss-3.17.3-2.fc21.x86_64                                   20/83 
  Updating   : nss-sysinit-3.17.3-2.fc21.x86_64                           21/83 
  Updating   : libcurl-7.37.0-11.fc21.x86_64                              22/83 
  Updating   : curl-7.37.0-11.fc21.x86_64                                 23/83 
  Updating   : rpm-plugin-selinux-4.12.0.1-4.fc21.x86_64                  24/83 
  Updating   : rpm-libs-4.12.0.1-4.fc21.x86_64                            25/83 
  Updating   : rpm-4.12.0.1-4.fc21.x86_64                                 26/83 
  Updating   : rpm-build-libs-4.12.0.1-4.fc21.x86_64                      27/83 
  Updating   : gettext-libs-0.19.4-2.fc21.x86_64                          28/83 
  Updating   : gettext-0.19.4-2.fc21.x86_64                               29/83 
install-info: No such file or directory for /usr/share/info/gettext.info.gz
  Updating   : 1:dbus-libs-1.8.12-3.fc21.x86_64                           30/83 
  Updating   : systemd-216-13.fc21.x86_64                                 31/83 
  Updating   : 1:dbus-1.8.12-3.fc21.x86_64                                32/83 
  Updating   : os-prober-1.65-2.fc21.x86_64                               33/83 
  Updating   : 1:grub2-tools-2.02-0.13.fc21.x86_64                        34/83 
  Updating   : firewalld-config-standard-0.3.13-1.fc21.noarch             35/83 
  Updating   : firewalld-0.3.13-1.fc21.noarch                             36/83 
  Updating   : dracut-038-32.git20141216.fc21.x86_64                      37/83 
  Updating   : 1:grub2-2.02-0.13.fc21.x86_64                              38/83 
  Updating   : rpm-python-4.12.0.1-4.fc21.x86_64                          39/83 
  Updating   : nss-tools-3.17.3-2.fc21.x86_64                             40/83 
  Updating   : gpgme-1.4.3-5.fc21.x86_64                                  41/83 
  Updating   : tzdata-2014j-1.fc21.noarch                                 42/83 
  Cleanup    : 1:grub2-2.02-0.11.fc21.x86_64                              43/83 
  Cleanup    : firewalld-config-standard-0.3.12-1.fc21.noarch             44/83 
  Cleanup    : firewalld-0.3.12-1.fc21.noarch                             45/83 
  Cleanup    : tzdata-2014i-1.fc21.noarch                                 46/83 
  Cleanup    : dracut-038-30.git20140903.fc21.x86_64                      47/83 
  Cleanup    : nss-tools-3.17.2-1.fc21.x86_64                             48/83 
  Cleanup    : rpm-python-4.12.0.1-3.fc21.x86_64                          49/83 
  Cleanup    : 1:grub2-tools-2.02-0.11.fc21.x86_64                        50/83 
  Cleanup    : os-prober-1.58-11.fc21.x86_64                              51/83 
  Cleanup    : 1:dbus-1.8.6-3.fc21.x86_64                                 52/83 
  Cleanup    : systemd-216-12.fc21.x86_64                                 53/83 
  Cleanup    : util-linux-2.25.2-1.fc21.x86_64                            54/83 
  Cleanup    : libmount-2.25.2-1.fc21.x86_64                              55/83 
  Cleanup    : rpm-build-libs-4.12.0.1-3.fc21.x86_64                      56/83 
  Cleanup    : rpm-plugin-selinux-4.12.0.1-3.fc21.x86_64                  57/83 
  Cleanup    : rpm-libs-4.12.0.1-3.fc21.x86_64                            58/83 
  Cleanup    : rpm-4.12.0.1-3.fc21.x86_64                                 59/83 
  Cleanup    : curl-7.37.0-9.fc21.x86_64                                  60/83 
  Cleanup    : libcurl-7.37.0-9.fc21.x86_64                               61/83 
  Cleanup    : nss-sysinit-3.17.2-1.fc21.x86_64                           62/83 
  Cleanup    : nss-3.17.2-1.fc21.x86_64                                   63/83 
  Cleanup    : nss-softokn-3.17.2-1.fc21.x86_64                           64/83 
  Cleanup    : libblkid-2.25.2-1.fc21.x86_64                              65/83 
  Cleanup    : kmod-18-4.fc21.x86_64                                      66/83 
  Cleanup    : grep-2.20-6.fc21.x86_64                                    67/83 
  Cleanup    : gettext-0.19.2-6.fc21.x86_64                               68/83 
  Cleanup    : procps-ng-3.3.10-4.fc21.x86_64                             69/83 
  Cleanup    : filesystem-3.2-27.fc21.x86_64                              70/83 
  Cleanup    : systemd-libs-216-12.fc21.x86_64                            71/83 
  Cleanup    : gettext-libs-0.19.2-6.fc21.x86_64                          72/83 
  Cleanup    : pcre-8.35-7.fc21.x86_64                                    73/83 
  Cleanup    : kmod-libs-18-4.fc21.x86_64                                 74/83 
  Cleanup    : libuuid-2.25.2-1.fc21.x86_64                               75/83 
  Cleanup    : nss-util-3.17.2-1.fc21.x86_64                              76/83 
  Cleanup    : sqlite-3.8.7-1.fc21.x86_64                                 77/83 
  Cleanup    : nss-softokn-freebl-3.17.2-1.fc21.x86_64                    78/83 
  Cleanup    : libsmartcols-2.25.2-1.fc21.x86_64                          79/83 
  Cleanup    : 1:dbus-libs-1.8.6-3.fc21.x86_64                            80/83 
  Cleanup    : freetype-2.5.3-11.fc21.x86_64                              81/83 
  Cleanup    : cpio-2.11-30.fc21.x86_64                                   82/83 
  Cleanup    : gpgme-1.4.3-4.fc21.x86_64                                  83/83 
  Verifying  : 1:grub2-2.02-0.13.fc21.x86_64                               1/83 
  Verifying  : 1:dbus-libs-1.8.12-3.fc21.x86_64                            2/83 
  Verifying  : libcurl-7.37.0-11.fc21.x86_64                               3/83 
  Verifying  : tzdata-2014j-1.fc21.noarch                                  4/83 
  Verifying  : nss-util-3.17.3-1.fc21.x86_64                               5/83 
  Verifying  : nss-softokn-3.17.3-1.fc21.x86_64                            6/83 
  Verifying  : libmount-2.25.2-2.fc21.x86_64                               7/83 
  Verifying  : libblkid-2.25.2-2.fc21.x86_64                               8/83 
  Verifying  : systemd-216-13.fc21.x86_64                                  9/83 
  Verifying  : rpm-python-4.12.0.1-4.fc21.x86_64                          10/83 
  Verifying  : gettext-libs-0.19.4-2.fc21.x86_64                          11/83 
  Verifying  : libuuid-2.25.2-2.fc21.x86_64                               12/83 
  Verifying  : rpm-plugin-selinux-4.12.0.1-4.fc21.x86_64                  13/83 
  Verifying  : kmod-libs-19-1.fc21.x86_64                                 14/83 
  Verifying  : sqlite-3.8.7.4-1.fc21.x86_64                               15/83 
  Verifying  : pcre-8.35-8.fc21.x86_64                                    16/83 
  Verifying  : firewalld-0.3.13-1.fc21.noarch                             17/83 
  Verifying  : rpm-4.12.0.1-4.fc21.x86_64                                 18/83 
  Verifying  : rpm-build-libs-4.12.0.1-4.fc21.x86_64                      19/83 
  Verifying  : util-linux-2.25.2-2.fc21.x86_64                            20/83 
  Verifying  : nss-3.17.3-2.fc21.x86_64                                   21/83 
  Verifying  : 1:dbus-1.8.12-3.fc21.x86_64                                22/83 
  Verifying  : freetype-2.5.3-13.fc21.x86_64                              23/83 
  Verifying  : os-prober-1.65-2.fc21.x86_64                               24/83 
  Verifying  : firewalld-config-standard-0.3.13-1.fc21.noarch             25/83 
  Verifying  : libsmartcols-2.25.2-2.fc21.x86_64                          26/83 
  Verifying  : curl-7.37.0-11.fc21.x86_64                                 27/83 
  Verifying  : gpgme-1.4.3-5.fc21.x86_64                                  28/83 
  Verifying  : rpm-libs-4.12.0.1-4.fc21.x86_64                            29/83 
  Verifying  : gettext-0.19.4-2.fc21.x86_64                               30/83 
  Verifying  : filesystem-3.2-28.fc21.x86_64                              31/83 
  Verifying  : nss-sysinit-3.17.3-2.fc21.x86_64                           32/83 
  Verifying  : grep-2.21-1.fc21.x86_64                                    33/83 
  Verifying  : dracut-038-32.git20141216.fc21.x86_64                      34/83 
  Verifying  : kmod-19-1.fc21.x86_64                                      35/83 
  Verifying  : nss-softokn-freebl-3.17.3-1.fc21.x86_64                    36/83 
  Verifying  : 1:grub2-tools-2.02-0.13.fc21.x86_64                        37/83 
  Verifying  : firewalld-filesystem-0.3.13-1.fc21.noarch                  38/83 
  Verifying  : cpio-2.11-33.fc21.x86_64                                   39/83 
  Verifying  : procps-ng-3.3.10-5.fc21.x86_64                             40/83 
  Verifying  : nss-tools-3.17.3-2.fc21.x86_64                             41/83 
  Verifying  : systemd-libs-216-13.fc21.x86_64                            42/83 
  Verifying  : curl-7.37.0-9.fc21.x86_64                                  43/83 
  Verifying  : kmod-libs-18-4.fc21.x86_64                                 44/83 
  Verifying  : gettext-0.19.2-6.fc21.x86_64                               45/83 
  Verifying  : os-prober-1.58-11.fc21.x86_64                              46/83 
  Verifying  : systemd-libs-216-12.fc21.x86_64                            47/83 
  Verifying  : nss-util-3.17.2-1.fc21.x86_64                              48/83 
  Verifying  : firewalld-config-standard-0.3.12-1.fc21.noarch             49/83 
  Verifying  : 1:dbus-libs-1.8.6-3.fc21.x86_64                            50/83 
  Verifying  : libsmartcols-2.25.2-1.fc21.x86_64                          51/83 
  Verifying  : procps-ng-3.3.10-4.fc21.x86_64                             52/83 
  Verifying  : gettext-libs-0.19.2-6.fc21.x86_64                          53/83 
  Verifying  : dracut-038-30.git20140903.fc21.x86_64                      54/83 
  Verifying  : firewalld-0.3.12-1.fc21.noarch                             55/83 
  Verifying  : 1:dbus-1.8.6-3.fc21.x86_64                                 56/83 
  Verifying  : nss-softokn-freebl-3.17.2-1.fc21.x86_64                    57/83 
  Verifying  : libblkid-2.25.2-1.fc21.x86_64                              58/83 
  Verifying  : util-linux-2.25.2-1.fc21.x86_64                            59/83 
  Verifying  : rpm-build-libs-4.12.0.1-3.fc21.x86_64                      60/83 
  Verifying  : freetype-2.5.3-11.fc21.x86_64                              61/83 
  Verifying  : libuuid-2.25.2-1.fc21.x86_64                               62/83 
  Verifying  : 1:grub2-2.02-0.11.fc21.x86_64                              63/83 
  Verifying  : nss-tools-3.17.2-1.fc21.x86_64                             64/83 
  Verifying  : nss-3.17.2-1.fc21.x86_64                                   65/83 
  Verifying  : 1:grub2-tools-2.02-0.11.fc21.x86_64                        66/83 
  Verifying  : pcre-8.35-7.fc21.x86_64                                    67/83 
  Verifying  : rpm-4.12.0.1-3.fc21.x86_64                                 68/83 
  Verifying  : rpm-plugin-selinux-4.12.0.1-3.fc21.x86_64                  69/83 
  Verifying  : grep-2.20-6.fc21.x86_64                                    70/83 
  Verifying  : sqlite-3.8.7-1.fc21.x86_64                                 71/83 
  Verifying  : filesystem-3.2-27.fc21.x86_64                              72/83 
  Verifying  : rpm-libs-4.12.0.1-3.fc21.x86_64                            73/83 
  Verifying  : kmod-18-4.fc21.x86_64                                      74/83 
  Verifying  : nss-sysinit-3.17.2-1.fc21.x86_64                           75/83 
  Verifying  : tzdata-2014i-1.fc21.noarch                                 76/83 
  Verifying  : cpio-2.11-30.fc21.x86_64                                   77/83 
  Verifying  : libcurl-7.37.0-9.fc21.x86_64                               78/83 
  Verifying  : rpm-python-4.12.0.1-3.fc21.x86_64                          79/83 
  Verifying  : gpgme-1.4.3-4.fc21.x86_64                                  80/83 
  Verifying  : nss-softokn-3.17.2-1.fc21.x86_64                           81/83 
  Verifying  : systemd-216-12.fc21.x86_64                                 82/83 
  Verifying  : libmount-2.25.2-1.fc21.x86_64                              83/83 

Dependency Installed:
  firewalld-filesystem.noarch 0:0.3.13-1.fc21                                   

Updated:
  cpio.x86_64 0:2.11-33.fc21                                                    
  curl.x86_64 0:7.37.0-11.fc21                                                  
  dbus.x86_64 1:1.8.12-3.fc21                                                   
  dbus-libs.x86_64 1:1.8.12-3.fc21                                              
  dracut.x86_64 0:038-32.git20141216.fc21                                       
  filesystem.x86_64 0:3.2-28.fc21                                               
  firewalld.noarch 0:0.3.13-1.fc21                                              
  firewalld-config-standard.noarch 0:0.3.13-1.fc21                              
  freetype.x86_64 0:2.5.3-13.fc21                                               
  gettext.x86_64 0:0.19.4-2.fc21                                                
  gettext-libs.x86_64 0:0.19.4-2.fc21                                           
  gpgme.x86_64 0:1.4.3-5.fc21                                                   
  grep.x86_64 0:2.21-1.fc21                                                     
  grub2.x86_64 1:2.02-0.13.fc21                                                 
  grub2-tools.x86_64 1:2.02-0.13.fc21                                           
  kmod.x86_64 0:19-1.fc21                                                       
  kmod-libs.x86_64 0:19-1.fc21                                                  
  libblkid.x86_64 0:2.25.2-2.fc21                                               
  libcurl.x86_64 0:7.37.0-11.fc21                                               
  libmount.x86_64 0:2.25.2-2.fc21                                               
  libsmartcols.x86_64 0:2.25.2-2.fc21                                           
  libuuid.x86_64 0:2.25.2-2.fc21                                                
  nss.x86_64 0:3.17.3-2.fc21                                                    
  nss-softokn.x86_64 0:3.17.3-1.fc21                                            
  nss-softokn-freebl.x86_64 0:3.17.3-1.fc21                                     
  nss-sysinit.x86_64 0:3.17.3-2.fc21                                            
  nss-tools.x86_64 0:3.17.3-2.fc21                                              
  nss-util.x86_64 0:3.17.3-1.fc21                                               
  os-prober.x86_64 0:1.65-2.fc21                                                
  pcre.x86_64 0:8.35-8.fc21                                                     
  procps-ng.x86_64 0:3.3.10-5.fc21                                              
  rpm.x86_64 0:4.12.0.1-4.fc21                                                  
  rpm-build-libs.x86_64 0:4.12.0.1-4.fc21                                       
  rpm-libs.x86_64 0:4.12.0.1-4.fc21                                             
  rpm-plugin-selinux.x86_64 0:4.12.0.1-4.fc21                                   
  rpm-python.x86_64 0:4.12.0.1-4.fc21                                           
  sqlite.x86_64 0:3.8.7.4-1.fc21                                                
  systemd.x86_64 0:216-13.fc21                                                  
  systemd-libs.x86_64 0:216-13.fc21                                             
  tzdata.noarch 0:2014j-1.fc21                                                  
  util-linux.x86_64 0:2.25.2-2.fc21                                             

Complete!
Cleaning repos: fedora updates
Cleaning up everything
 ---> 3af8a8447d8e
Removing intermediate container abf6034f4b03
Step 3 : RUN yum -y install openssh-server && yum clean all
 ---> Running in ea430fc3c22d
Resolving Dependencies
--> Running transaction check
---> Package openssh-server.x86_64 0:6.6.1p1-9.fc21 will be installed
--> Processing Dependency: openssh = 6.6.1p1-9.fc21 for package: openssh-server-6.6.1p1-9.fc21.x86_64
--> Processing Dependency: libwrap.so.0()(64bit) for package: openssh-server-6.6.1p1-9.fc21.x86_64
--> Running transaction check
---> Package openssh.x86_64 0:6.6.1p1-9.fc21 will be installed
---> Package tcp_wrappers-libs.x86_64 0:7.6-79.fc21 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                 Arch         Version               Repository     Size
================================================================================
Installing:
 openssh-server          x86_64       6.6.1p1-9.fc21        updates       437 k
Installing for dependencies:
 openssh                 x86_64       6.6.1p1-9.fc21        updates       437 k
 tcp_wrappers-libs       x86_64       7.6-79.fc21           fedora         70 k

Transaction Summary
================================================================================
Install  1 Package (+2 Dependent packages)

Total download size: 945 k
Installed size: 2.4 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                              273 kB/s | 945 kB  00:03     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : tcp_wrappers-libs-7.6-79.fc21.x86_64                         1/3 
  Installing : openssh-6.6.1p1-9.fc21.x86_64                                2/3 
  Installing : openssh-server-6.6.1p1-9.fc21.x86_64                         3/3 
  Verifying  : openssh-6.6.1p1-9.fc21.x86_64                                1/3 
  Verifying  : openssh-server-6.6.1p1-9.fc21.x86_64                         2/3 
  Verifying  : tcp_wrappers-libs-7.6-79.fc21.x86_64                         3/3 

Installed:
  openssh-server.x86_64 0:6.6.1p1-9.fc21                                        

Dependency Installed:
  openssh.x86_64 0:6.6.1p1-9.fc21     tcp_wrappers-libs.x86_64 0:7.6-79.fc21    

Complete!
Cleaning repos: fedora updates
Cleaning up everything
 ---> aa5e2d3684f9
Removing intermediate container ea430fc3c22d
Step 4 : ADD ./start.sh /start.sh
 ---> 638b199b25d2
Removing intermediate container fefe565d046a
Step 5 : RUN mkdir /var/run/sshd
 ---> Running in 7a5e367333fa
 ---> 9410b37010c7
Removing intermediate container 7a5e367333fa
Step 6 : RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
 ---> Running in 6dd6645ec623
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
The key fingerprint is:
03:c3:6b:1b:7e:3d:42:95:68:d1:d5:c5:36:02:10:8a root@c4e263145f81
The key's randomart image is:
+--[ RSA 2048]----+
|        .+ooo. o.|
|     .. .o.. ...o|
|     E+.o o   ...|
|       = .       |
|      + S        |
|     o + o       |
|      o o o      |
|       . . .     |
|                 |
+-----------------+
 ---> 568d372cb6e1
Removing intermediate container 6dd6645ec623
Step 7 : RUN chmod 755 /start.sh
 ---> Running in 8859d140fcd0
 ---> 47f50ac4ce60
Removing intermediate container 8859d140fcd0
Step 8 : RUN ./start.sh
 ---> Running in b2614be2ddbe
./start.sh: line 7: passwd: command not found
ssh user password: newpass
 ---> 54112ab06e1c
Removing intermediate container b2614be2ddbe
Step 9 : ENTRYPOINT /usr/sbin/sshd -D
 ---> Running in fc33b9ede80b
 ---> 880206f79e8c
Removing intermediate container fc33b9ede80b
Successfully built 880206f79e8c

**Comment by arun-gupta** [comment]
Rebuilding the image right away did not show that error again. Wondering if this is a first-time thing only.

**Comment by mikedep333** [comment]
Hi @arun-gupta

The `passwd` package needs to be installed or else the `/usr/bin/passwd` command is not present. 

With the current Fedora 21 ssh Dockerfile, `passwd` is not installed. I am surprised that rebuilding the image right away did not show that error.

Anyway, I will submit a PR to fix this.
