### ISSUE TITLE
Cannot run the container with "ssh" image

### ISSUE THREAD

**Issue by arun-gupta** [fedora-cloud/Fedora-Dockerfiles#66]
Running the container throws the following error:

ssh -p 10022 user@192.168.59.103
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
03:c3:6b:1b:7e:3d:42:95:68:d1:d5:c5:36:02:10:8a.
Please contact your system administrator.
Add correct host key in /Users/arungupta/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/arungupta/.ssh/known_hosts:169
RSA host key for [192.168.59.103]:10022 has changed and you have requested strict checking.
Host key verification failed.

**Comment by goldmann** [comment]
I guess this is not an issue with the image, you have use the `192.168.59.103` host previously and the identity is now cached, run: `ssh-keygen -r 192.168.59.103` to clear it.

**Comment by arun-gupta** [comment]
ssh-keygen -r 192.168.59.103 says "no keys found.".

**Comment by goldmann** [comment]
Sorry, it should be `ssh-keygen -R 192.168.59.103`.

**Comment by arun-gupta** [comment]
It gives:

ssh-keygen -R 192.168.59.103
/Users/arungupta/.ssh/known_hosts updated.
Original contents retained as /Users/arungupta/.ssh/known_hosts.old

Running the container gives the same error though.

**Comment by arielb2** [comment]
try deleting the line  169 in /Users/arungupta/.ssh/known_hosts
"Offending RSA key in /Users/arungupta/.ssh/known_hosts:169"

**Comment by arun-gupta** [comment]
That allowed to move forward but giving the command

ssh -p 10022 user@192.168.59.103

and using the password "newpass" gives permission denied.

Building the image also gave:

 ---> Running in 58c703a0501a
./start.sh: line 7: passwd: command not found
ssh user password: newpass

Wondering if this is related to #65

**Comment by scollier** [comment]
should be fixed now
